name: Deploy to Google Cloud
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**'
jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE: gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_SERVICE }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Authenticate Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCLOUD_APPS_CREDENTIALS }}
    - name: Configure Docker
      run: gcloud auth configure-docker --quiet
    - name: Build Docker Image
      run: docker build . -t $IMAGE
    - name: Push Docker Image
      run: docker push $IMAGE
    - name: Delay
      run: sleep 5
    - name: Deploy to Google Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ secrets.GCLOUD_SERVICE }}
        image: ${{ env.IMAGE }}
        env_vars: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}